[The Guardian]
title = "The Guardian international"
url = "https://www.theguardian.com/international"
entrySelector = "#headlines"
titleSelector = ".fc-slice-wrapper"
linkSelector = ".u-faux-block-link__overlay"
